apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sr826zvzn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sr826zvzn-nodejs 
  name: sr826zvzn-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: sr826zvzn-nodejs 
